name = "jsonhero-io"
type = "javascript"
compatibility_date = "2022-02-01"

account_id = "0cf692be2d4cc5827c7ba87ae5bc34ce"
workers_dev = true

kv_namespaces = [
  { binding = "DOCUMENTS", id = "4124fe171f0e4890b39fcfe7c931035e" }
]

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"

route = "jsonhero.atsud0.me/*"
zone_id = "9185dcbba83e4df397bc0ee52d63b457"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format = "service-worker"

# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [APIHERO_PROJECT_KEY]
